---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: msp
type: Opaque
stringData:
  JWT_SECRET: "REPLACE_WITH_AT_LEAST_32_CHARACTERS_OF_RANDOM_BYTES"
  MONGO_URI_AUTH:    "mongodb://mongodb-service.msp.svc.cluster.local:27017/auth_db"
  MONGO_URI_STUDENT: "mongodb://mongodb-service.msp.svc.cluster.local:27017/student_db"
  MONGO_URI_TEACHER: "mongodb://mongodb-service.msp.svc.cluster.local:27017/teacher_db"
