apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: aupp

resources:
  - namespace.yaml
  - secret.yaml
  - mongodb.yaml
  - login-service.yaml
  - teacher-service.yaml
  - student-service.yaml
  - api-gateway.yaml
