apiVersion: apps/v1
kind: Deployment
metadata:
  name: teacher-service
  labels:
    app: teacher-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: teacher-service
  template:
    metadata:
      labels:
        app: teacher-service
    spec:
      nodeSelector:
        role: teacher
      containers:
        - name: teacher-service
          image: dapravith99/teacher-service:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8083
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: MONGO_URI
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: JWT_SECRET
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8083
            initialDelaySeconds: 20
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8083
            initialDelaySeconds: 60
            periodSeconds: 15
          resources:
            requests:
              cpu: 50m
              memory: 192Mi
            limits:
              cpu: 500m
              memory: 384Mi
---
apiVersion: v1
kind: Service
metadata:
  name: teacher-service
spec:
  selector:
    app: teacher-service
  ports:
    - name: http
      port: 8083
      targetPort: 8083
  type: ClusterIP
