server:
  port: ${PORT:8082}

spring:
  application:
    name: student-service
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://mongodb:27017/student_db}

management:
  endpoints:
    web:
      exposure:
        include: health,info
