apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: student-vol1
  namespace: aupp
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-service
  namespace: aupp
  labels: { app: student-service }
spec:
  replicas: 1
  selector:
    matchLabels: { app: student-service }
  template:
    metadata:
      labels: { app: student-service }
    spec:
      # Pin to EC2-2 (Vol 1 in the architecture diagram)
      nodeSelector:
        role: student
      containers:
        - name: student-service
          image: aupp/student-service:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8082
          env:
            - name: MONGO_URI
              value: "mongodb://mongodb.aupp.svc.cluster.local:27017/student_db"
          volumeMounts:
            - name: vol1
              mountPath: /var/data/student
          readinessProbe:
            httpGet: { path: /actuator/health, port: 8082 }
            initialDelaySeconds: 20
            periodSeconds: 5
          livenessProbe:
            httpGet: { path: /actuator/health, port: 8082 }
            initialDelaySeconds: 60
            periodSeconds: 15
          resources:
            requests: { cpu: "50m",  memory: "192Mi" }
            limits:   { cpu: "500m", memory: "384Mi" }
      volumes:
        - name: vol1
          persistentVolumeClaim:
            claimName: student-vol1
---
apiVersion: v1
kind: Service
metadata:
  name: student-service
  namespace: aupp
spec:
  selector: { app: student-service }
  ports:
    - name: http
      port: 8082
      targetPort: 8082
  type: ClusterIP
