---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication-service
  namespace: msp
  labels:
    app: authentication-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authentication-service
  template:
    metadata:
      labels:
        app: authentication-service
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: role
                    operator: In
                    values: [frontend]
      containers:
        - name: authentication-service
          image: DOCKERHUB_USER/ms-login:1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 5002
          env:
            - name: PORT
              value: "5002"
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: MONGO_URI_AUTH
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: JWT_SECRET
            - name: JAVA_OPTS
              value: "-XX:MaxRAMPercentage=75 -Djava.security.egd=file:/dev/./urandom"
          readinessProbe:
            httpGet: { path: /actuator/health/readiness, port: 5002 }
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 3
          livenessProbe:
            httpGet: { path: /actuator/health/liveness, port: 5002 }
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 3
          resources:
            requests: { cpu: 100m, memory: 256Mi }
            limits:   { cpu: 1000m, memory: 768Mi }
