---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /var/lib/mongo-data
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: db
              operator: In
              values:
                - mongo

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: msp
  labels:
    app: mongodb
spec:
  serviceName: mongodb-service
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      # CRITICAL FIX: Gives the MongoDB container (User 999) permission to write to the local EC2 folder
      securityContext:
        fsGroup: 999
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: db
                    operator: In
                    values:
                      - mongo
      containers:
        - name: mongodb
          image: mongo:7
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-data # Must match the volumeClaimTemplate name below
              mountPath: /data/db
          readinessProbe:
            exec:
              command: ["mongosh", "--quiet", "--eval", "db.runCommand({ ping: 1 }).ok"]
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            exec:
              command: ["mongosh", "--quiet", "--eval", "db.runCommand({ ping: 1 }).ok"]
            initialDelaySeconds: 30
            periodSeconds: 30
          resources:
            requests: { cpu: 100m, memory: 256Mi }
            limits:   { cpu: 1000m, memory: 1Gi }

  # BEST PRACTICE: StatefulSets generate their own PVCs dynamically
  volumeClaimTemplates:
    - metadata:
        name: mongo-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: local-storage
        resources:
          requests:
            storage: 5Gi

---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: msp
spec:
  clusterIP: None
  selector:
    app: mongodb
  ports:
    - port: 27017
      targetPort: 27017