---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-service
  namespace: msp
  labels:
    app: student-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: student-service
  template:
    metadata:
      labels:
        app: student-service
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: role
                    operator: In
                    values: [student]
      containers:
        - name: student
          image: DOCKERHUB_USER/ms-student:1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: PORT
              value: "5000"
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: MONGO_URI_STUDENT
            - name: JAVA_OPTS
              value: "-XX:MaxRAMPercentage=75 -Djava.security.egd=file:/dev/./urandom"
          volumeMounts:
            - name: vol1
              mountPath: /var/data/student
          readinessProbe:
            httpGet: { path: /actuator/health/readiness, port: 5000 }
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 3
          livenessProbe:
            httpGet: { path: /actuator/health/liveness, port: 5000 }
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 3
          resources:
            requests: { cpu: 100m, memory: 256Mi }
            limits:   { cpu: 1000m, memory: 768Mi }
      volumes:
        - name: vol1
          emptyDir: {}
