server:
  port: ${PORT:8083}

spring:
  application:
    name: teacher-service
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://mongodb:27017/teacher_db}

management:
  endpoints:
    web:
      exposure:
        include: health,info
