spring:
  application:
    name: teacher-service
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://localhost:27017/teacher_db}
      auto-index-creation: true
  jackson:
    default-property-inclusion: non_null

server:
  port: ${PORT:5001}
  shutdown: graceful

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
      show-details: never

logging:
  level:
    root: INFO
    com.aupp: INFO
    org.springframework.data.mongodb: WARN
